[config]
unstable_features = ["CTRL_C_HANDLING"]
default_to_workspace = false

[tasks.tw-watch]
script = "yarn tailwindcss -i ./style/input.css -o ./style/output.css --watch"

[tasks.site-watch]
script = "cargo leptos watch"